version: "3.8"

services:
    chaturbate-dvr:
        image: zihaofu245/cdvr:latest
        container_name: chaturbate-dvr
        ports:
            - "8080:8080"
        volumes:
            - ./videos:/usr/src/app/videos
            - ./conf:/usr/src/app/conf
